sudo: required
langauge: generic

services:
  -docker

before_install:
  - docker build -t lfakroodeen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lfakroodeen/react-test npm test

after_success:
  - docker build -t lfakroodeen/multi-client ./client
  - docker build -t lfakroodeen/multi-nginx ./nginx
  - docker build -t lfakroodeen/multi-server ./server
  - docker build -t lfakroodeen/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing the images to docker hub
  - docker push lfakroodeen/multi-client
  - docker push lfakroodeen/multi-nginx
  - docker push lfakroodeen/multi-server
  - docker push lfakroodeen/multi-worker